import { useState } from 'react';
import { useAuth } from './useAuth';
import { useFinancialData, useTasks, useMoodLogs } from './useDatabase';
import { useToast } from './use-toast';

export const useExport = () => {
  const { user } = useAuth();
  const { financialData } = useFinancialData();
  const { tasks } = useTasks();
  const { moodLogs } = useMoodLogs();
  const { toast } = useToast();
  const [exporting, setExporting] = useState(false);

  const generateCSV = (data: any[], filename: string) => {
    if (data.length === 0) {
      toast({
        title: "No Data",
        description: `No ${filename.toLowerCase()} data to export.`,
        variant: "destructive",
      });
      return;
    }

    const headers = Object.keys(data[0]);
    const csvContent = [
      headers.join(','),
      ...data.map(row => 
        headers.map(header => {
          const value = row[header];
          // Handle arrays and objects
          if (Array.isArray(value)) {
            return `"${value.join('; ')}"`;
          }
          if (typeof value === 'object' && value !== null) {
            return `"${JSON.stringify(value)}"`;
          }
          // Escape commas and quotes
          const stringValue = String(value || '');
          if (stringValue.includes(',') || stringValue.includes('"')) {
            return `"${stringValue.replace(/"/g, '""')}"`;
          }
          return stringValue;
        }).join(',')
      )
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}_${new Date().toISOString().split('T')[0]}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const generatePDF = async (data: any[], title: string) => {
    // Simple HTML to PDF conversion
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} Report</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #059669; border-bottom: 2px solid #059669; padding-bottom: 10px; }
            h2 { color: #065f46; margin-top: 30px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; }
            .summary { background-color: #f0fdf4; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
            .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>JOOD AI - ${title} Report</h1>
          <div class="summary">
            <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
            <p><strong>User:</strong> ${user?.email}</p>
            <p><strong>Total Records:</strong> ${data.length}</p>
          </div>
          ${generateTableHTML(data, title)}
          <div class="footer">
            <p>Generated by JOOD AI - Your Elegant Financial Secretary</p>
          </div>
        </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
  };

  const generateTableHTML = (data: any[], title: string) => {
    if (data.length === 0) return '<p>No data available.</p>';

    const headers = Object.keys(data[0]);
    return `
      <table>
        <thead>
          <tr>
            ${headers.map(header => `<th>${header.replace(/_/g, ' ').toUpperCase()}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${data.map(row => `
            <tr>
              ${headers.map(header => {
                const value = row[header];
                if (Array.isArray(value)) {
                  return `<td>${value.join(', ')}</td>`;
                }
                if (typeof value === 'object' && value !== null) {
                  return `<td>${JSON.stringify(value)}</td>`;
                }
                return `<td>${value || ''}</td>`;
              }).join('')}
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;
  };

  const exportFinancialData = async (format: 'csv' | 'pdf') => {
    if (!user) return;
    
    try {
      setExporting(true);
      
      if (format === 'csv') {
        generateCSV(financialData, 'Financial_Data');
      } else {
        await generatePDF(financialData, 'Financial Data');
      }
      
      toast({
        title: "Export Successful",
        description: `Financial data exported as ${format.toUpperCase()}.`,
      });
    } catch (error) {
      console.error('Export error:', error);
      toast({
        title: "Export Failed",
        description: "Failed to export financial data.",
        variant: "destructive",
      });
    } finally {
      setExporting(false);
    }
  };

  const exportTasks = async (format: 'csv' | 'pdf') => {
    if (!user) return;
    
    try {
      setExporting(true);
      
      if (format === 'csv') {
        generateCSV(tasks, 'Tasks');
      } else {
        await generatePDF(tasks, 'Tasks');
      }
      
      toast({
        title: "Export Successful",
        description: `Tasks exported as ${format.toUpperCase()}.`,
      });
    } catch (error) {
      console.error('Export error:', error);
      toast({
        title: "Export Failed",
        description: "Failed to export tasks.",
        variant: "destructive",
      });
    } finally {
      setExporting(false);
    }
  };

  const exportMoodData = async (format: 'csv' | 'pdf') => {
    if (!user) return;
    
    try {
      setExporting(true);
      
      if (format === 'csv') {
        generateCSV(moodLogs, 'Mood_Data');
      } else {
        await generatePDF(moodLogs, 'Mood Data');
      }
      
      toast({
        title: "Export Successful",
        description: `Mood data exported as ${format.toUpperCase()}.`,
      });
    } catch (error) {
      console.error('Export error:', error);
      toast({
        title: "Export Failed",
        description: "Failed to export mood data.",
        variant: "destructive",
      });
    } finally {
      setExporting(false);
    }
  };

  const exportAllData = async (format: 'csv' | 'pdf') => {
    if (!user) return;
    
    try {
      setExporting(true);
      
      // Create comprehensive report
      const allData = {
        financial: financialData,
        tasks: tasks,
        mood: moodLogs,
        summary: {
          totalFinancialEntries: financialData.length,
          totalTasks: tasks.length,
          completedTasks: tasks.filter(t => t.status === 'completed').length,
          totalMoodEntries: moodLogs.length,
          averageMood: moodLogs.length > 0 
            ? (moodLogs.reduce((sum, log) => sum + log.mood_score, 0) / moodLogs.length).toFixed(1)
            : 'N/A'
        }
      };
      
      if (format === 'csv') {
        // Export each category separately
        generateCSV(financialData, 'Financial_Data');
        generateCSV(tasks, 'Tasks');
        generateCSV(moodLogs, 'Mood_Data');
      } else {
        const htmlContent = `
          <!DOCTYPE html>
          <html>
            <head>
              <title>JOOD AI - Complete Report</title>
              <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #059669; border-bottom: 2px solid #059669; padding-bottom: 10px; }
                h2 { color: #065f46; margin-top: 30px; }
                .summary { background-color: #f0fdf4; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
                .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin-top: 10px; }
                .summary-item { background: white; padding: 10px; border-radius: 5px; border-left: 4px solid #059669; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
                th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
                th { background-color: #f2f2f2; }
                .footer { margin-top: 30px; text-align: center; color: #666; font-size: 12px; }
              </style>
            </head>
            <body>
              <h1>JOOD AI - Complete Personal Report</h1>
              <div class="summary">
                <h3>Report Summary</h3>
                <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
                <p><strong>User:</strong> ${user?.email}</p>
                <div class="summary-grid">
                  <div class="summary-item">
                    <strong>Financial Entries:</strong> ${allData.summary.totalFinancialEntries}
                  </div>
                  <div class="summary-item">
                    <strong>Total Tasks:</strong> ${allData.summary.totalTasks}
                  </div>
                  <div class="summary-item">
                    <strong>Completed Tasks:</strong> ${allData.summary.completedTasks}
                  </div>
                  <div class="summary-item">
                    <strong>Average Mood:</strong> ${allData.summary.averageMood}/10
                  </div>
                </div>
              </div>
              
              <h2>Financial Data</h2>
              ${generateTableHTML(financialData, 'Financial')}
              
              <h2>Tasks</h2>
              ${generateTableHTML(tasks, 'Tasks')}
              
              <h2>Mood Tracking</h2>
              ${generateTableHTML(moodLogs, 'Mood')}
              
              <div class="footer">
                <p>Generated by JOOD AI - Your Elegant Financial Secretary</p>
              </div>
            </body>
          </html>
        `;

        const blob = new Blob([htmlContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        window.open(url, '_blank');
      }
      
      toast({
        title: "Export Successful",
        description: `Complete report exported as ${format.toUpperCase()}.`,
      });
    } catch (error) {
      console.error('Export error:', error);
      toast({
        title: "Export Failed",
        description: "Failed to export complete report.",
        variant: "destructive",
      });
    } finally {
      setExporting(false);
    }
  };

  return {
    exportFinancialData,
    exportTasks,
    exportMoodData,
    exportAllData,
    exporting,
  };
};